config/routes.rb
Rails.application.routes.draw do
  resources :members do
    resources :posts, module:  :members
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true
  validates :password, presence: true
  validates :email, presence: true

  has_many :posts, dependent: :destroy;
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :contents, presence: true
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members/posts_controller.rb
#DBRS class PostsController < ApplicationController
class Members::PostsController < ApplicationController
  before_action :set_member
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index

    #    @members = Post.all
    @posts = @member.posts
  end

  # GET /members/1 or /members/1.json
  def show
    # @post = Post.find(session[:post_id])
    #@post = Post.find params[:id]
  end
  # GET /members/new
  def new
    #    @post = Post.new
    @post = @member.posts.build
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    #    @post = Post.new(post_params)
    @post = @member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        #        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.html { redirect_to [@member, @post], notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        p "post_params"
        #        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.html { redirect_to [@member, @post], notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      #      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.html { redirect_to [@member, :posts], notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:member_id])
  end
  def set_post
    #   @post = Post.find(params[:id])
      @post = @member.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      #  params.require(:post).permit(:title, :member_id)
      params.require(:post).permit(:title, :contents)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        #        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        #        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :password, :email)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_member
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = @member.posts
    # @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    # @post = Post.find(session[:post_id])
    #@post = Post.find params[:id]
  end
  # GET /posts/new
  def new
    @post = @member.posts.build
    #@post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @member.posts.build(post_params)
    #@post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@member, @post], notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@member, @post], notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to [@member, :posts], notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:member_id])
  end
  def set_post
      @post = @member.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :contents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/eraseme/_form.html.erb
<%= form_with(model: [@member, post]) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :contents, style: "display: block" %>
    <%= form.text_field :contents %>
  </div>
<!--
  <div>
   < %= form.label :member_id, style: "display: block" %>
    < %= form.text_field :member_id %>
  </div>
-->
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/eraseme/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Contents:</strong>
    <%= post.contents %>
  </p>

  <p>
    <strong>Member:</strong>
    <%= post.member_id %>
  </p>

  <p>
    <%= link_to "Show this post", [@member, post] %>

  </p>

</div>

app/views/eraseme/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", [@member, @post] %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_member_post_path %>

app/views/eraseme/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to members", member_posts_path(@member) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemberOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= member.password %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= member.email %>
  </p>

  <p>
    <%= link_to "Show this member", member %>
  </p>

</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Members</h1>

<div id="members">
    <%= render @members %>
</div>

<%= link_to "New member", new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/posts/_form.html.erb
<%= form_with(model: [@member, post]) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :contents, style: "display: block" %>
    <%= form.text_field :contents %>
  </div>
<!--
  <div>
   < %= form.label :member_id, style: "display: block" %>
    < %= form.text_field :member_id %>
  </div>
-->
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Contents:</strong>
    <%= post.contents %>
  </p>

  <p>
    <strong>Member:</strong>
    <%= post.member_id %>
  </p>

  <p>
    <%= link_to "Show this post", [@member, post] %>

  </p>

</div>

app/views/members/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", [@member, @post] %> |
  <%= link_to "Back to members", member_posts_path(@member)%>
</div>

app/views/members/posts/index.html.erb
<p style="color: green" id="notice"><%= notice %></p>

<h1>Post</h1>

<div id="posts">
    <%= render @posts %>
 </div>

<%= link_to "New post", new_member_post_path %>

app/views/members/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to members", member_posts_path(@member) %>
</div>

app/views/members/posts/show.html.erb
<p style="color: green" id="notice"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_member_post_path([@member, @post]) %> |
  <%= link_to "Back to members", [@member, :posts] %>

  <%= button_to "Destroy this post", [@member, @post], method: :delete %>
</div>

app/views/members/show.html.erb
<p style="color: green" id="notice"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", member_path(@member), method: :delete %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", [@member, @post] %> |
  <%= link_to "Back to posts", member_posts_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", member_posts_path(@member) %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_member_post_path([@member, @post]) %> |
  <%= link_to "Back to posts", [@member, :posts] %>

  <%= button_to "Destroy this post", [@member, @post], method: :delete %>
</div>